# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "910e4f7d396dc57ccb819112a1d924bb"
name = "Farmacia Picual"
application_url = "https://99vh1p-pz.myshopify.com"
embedded = true

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_inventory,read_locations,write_merchant_managed_fulfillment_orders,read_orders,write_orders,read_customers,read_discounts,write_discounts,write_products,read_publications,write_publications,unauthenticated_write_checkouts,unauthenticated_read_checkouts,unauthenticated_read_product_listings,customer_read_customers,customer_read_orders"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ ]

[customer_authentication]
redirect_uris = [ "https://amapola-parafarmacia-actual.sergior500.chatgpt.site/api/customer/auth/callback" ]
javascript_origins = [ "https://amapola-parafarmacia-actual.sergior500.chatgpt.site" ]
logout_urls = [ "https://amapola-parafarmacia-actual.sergior500.chatgpt.site/cuenta?sesion=cerrada" ]
